#! /bin/bash
# Võtab parameetriks faili kasutajanimedega ja loob vastavalt sellele kasutajad kasutades
# varasemalt loodud skripti

if [ "$(id -u)" -ne 0 ]; then
    echo "Puuduvad õigused. Kasuta sudo või root skripti jooksutamiseks."
    exit 1
fi

if [ $# -ne 1 ];then
	echo "Kasutus: $0 kasutajate_fail"
else
	fail=$1
	if [ -f $fail -a -r $fail ]; then
		echo "Fail sobib"
		for nimi in $(cat $fail); do
			sh lisa_kasutaja $nimi
		done
	else
		echo "Probleem antud failiga $fail"
	fi
fi
